In [2]:
import numpy as np


In [47]:
#1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.
arr = np.arange(30)
newarr = arr.reshape(15, 2)
newarr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [52]:
#2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
arr = np.random.randint(0, 100, 60)
newarr = arr.reshape(4, 5, 3)
print(newarr.ndim)
print(newarr.shape)

3
(4, 5, 3)


In [58]:
#3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
arr = np.random.randint(0, 10, 20).reshape(4, 5)
newarr = arr.reshape(-1)
print(newarr.ndim)
print(newarr.shape)


1
(20,)


In [63]:
#4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("birinci yol ###################################")
for i in arr:
    for j in i:
        print(j)
print("ikinci yol ####################################")
for i in np.nditer(arr):
    print(i)

birinci yol ###################################
1
2
3
4
5
6
ikinci yol ####################################
1
2
3
4
5
6


In [70]:
#5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
#  1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
#   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.
arr1 = np.arange(5, 31, 5)
print(arr1)
print("#############")
arr2 = np.arange(7)
print(arr2)

toplama = arr1[1] + arr2[1]
cikarma = arr1[1] - arr2[1]
carpma = arr1[1] * arr2[1]
bolme = arr1[1] / arr2[1]

print(f"iki arrayin 1. indexlerinin toplamı : {toplama}")
print(f"iki arrayin 1. indexlerinin çıkarma işlemi : {cikarma}"),
print(f"iki arrayin 1. indexlerinin çarpması : {carpma}"),
print(f"iki arrayin 1. indexlerinin bölümü : {bolme}"),



[ 5 10 15 20 25 30]
#############
[0 1 2 3 4 5 6]
iki arrayin 1. indexlerinin toplamı : 11
iki arrayin 1. indexlerinin çıkarma işlemi : 9
iki arrayin 1. indexlerinin çarpması : 10
iki arrayin 1. indexlerinin bölümü : 10.0


(None,)

In [83]:
#6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.
arr = np.random.randint(0, 100, 10)
print(f"sum : {arr.sum()}\
        mean : {arr.mean()}\
        max : {arr.max()}\
        var : {arr.var()}\
        std : {arr.std()}")

sum : 630        mean : 63.0        max : 98        var : 534.2        std : 23.112767034693185


In [86]:
#7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.
arr1 = np.arange(20)
arr2 = np.arange(500, 531)
concatenate = np.concatenate([arr1 , arr2])
print(concatenate)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515
 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530]


In [91]:
#8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.
arr1 = np.arange(15, 51)
arr2 = np.arange(10, 101)
arr3 = np.concatenate((arr1, arr2))
arr3[25: 51] = 888
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
#9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.
arr1 = np.arange(40).reshape(8,5)
arr2 = np.arange(320,360).reshape(8,5)
conc1 = np.concatenate((arr1, arr2))
conc2 = np.concatenate((arr1, arr2), axis=1)
print(conc1)
print("################################")
print(conc2)

print(f"shape of conc1 : {conc1.shape}")
print(f"shape of conc2 : {conc2.shape}")

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]
################################
[[  0   1   2   3   4 320 321 322 323 324]
 [  5   6   7   8   9 325 326 327 328 329]
 [ 10  11  12  13  14 330 331 332 333 334]
 [ 15  16  17  18  19 335 336 337 338 339]
 [ 20  21  22  23  24 340 341 342 343 344]
 [ 25  26  27  28  29 345 346 347 348 349]
 [ 30  31  32  33  34 350 351 352 353 354]
 [ 35  36  37  38  39 355 356 357 358 359]]
shape of conc1 : (16, 5)
shape of conc2 : (8, 10)


In [5]:
#10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.
np.stack((arr1, arr2), axis=2)
# np.concatenate((arr1, arr2), axis=2) #hata alırız.

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

In [100]:
#11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.
arr = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
a = np.where(arr == 5)
a

(array([ 5, 13]),)

In [101]:
#12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.
b = np.where(arr % 2 == 0)
b

(array([ 1,  3,  4,  6,  7,  9, 11]),)

In [103]:
#13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.
c = np.where(arr > 4)
c

(array([ 1,  2,  5,  9, 10, 11, 13]),)

In [104]:
#14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.
d = np.where(arr % 5 == 0)
d

(array([ 1,  2,  5, 13]),)

In [105]:
np.random.randint(85,101)

89

In [107]:
#16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.
arr = np.random.randint(10,100,9).reshape(3,3)
arr

array([[17, 88, 46],
       [55, 66, 68],
       [32, 99, 36]])

In [111]:
#17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.
arr = np.arange(35, 60)
np.random.choice(arr)

45

In [3]:
#18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.
arr = np.random.choice([3, 8, 10, 53], size=(2,5))
arr

array([[53, 53, 53, 10,  8],
       [53, 10,  8, 10, 10]])