In [3]:
import numpy as np

In [6]:
#1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın.
#Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin

arr = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
arr
arr.ndim

3

In [7]:
#2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.
np.arange(34, 113, 6)

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [9]:
#3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)
np.linspace(50, 500, 91, dtype=int)

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

In [10]:
#4) 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.
np.logspace(2,5,8)

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

In [13]:
#5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.
arr = np.arange(0, 9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
#6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)
np.zeros((6,6), dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [19]:
#7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
#8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

np.eye(8, dtype=int)


array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [21]:
#9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)
arr = np.eye(5, dtype=int)
arr*3

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [22]:
#10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

np.random.rand(6)

array([0.03218947, 0.725381  , 0.27560993, 0.54539868, 0.17755762,
       0.25147533])

In [27]:
#11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

arr = np.random.randint(50, 101, 10).reshape(5, 2)
arr.shape

(5, 2)

In [31]:
#12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

arr = np.random.randint(100, 1000, 50).reshape(2, 5, 5)
print(arr.shape)
print(arr.ndim)

(2, 5, 5)
3


In [41]:
#13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.
arr = np.random.randint(0, 101, 10)
print(arr)
print("arrayin maksimum değeri : ", arr.max())
print("arrayin maksimum değerinin bulunduğu index : ", arr.argmax())
print("arrayin minimum değeri: ", arr.min())
print("arrayin minimum değerinin bulunduğu index : ", arr.argmin())

[65 52  8 32 16 87 98  2 29 52]
arrayin maksimum değeri :  98
arrayin maksimum değerinin bulunduğu index :  6
arrayin minimum değeri:  2
arrayin minimum değerinin bulunduğu index :  7


In [44]:
#14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.
arr = np.random.randint(300, 501, 20).reshape(2, 2, 5)
print(arr)
max_deger = arr[1, 1, 0]
min_deger = arr[1, 0, 0]
print(max_deger)
print(min_deger)

[[[423 425 438 437 468]
  [370 452 477 379 312]]

 [[304 458 318 488 387]
  [490 323 391 483 381]]]
381
423


In [46]:
#15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.
arr = np.arange(51)
arr[20:35] = 500
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50]
